services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - net
    depends_on:
      - postgres
  
  grafana:
    image: grafana/grafana-oss:8.4.3
    container_name: grafana
    depends_on:
      - postgres
    ports:
      - "3001:3000"
    networks:
      - net
    
networks:
  net:
    external: true

volumes:
  postgres_data:
